const instances=[['订单主库','mysql-prod-order-01','MySQL','运行中','42%',42],['用户中心','pgsql-user-primary','PostgreSQL','运行中','61%',61],['缓存集群','redis-session-01','Redis','运行中','28%',28],['分析从库','mysql-analytics-replica','MySQL','延迟告警','76%',76]];
const alerts=[['主从复制延迟过高','mysql-analytics-replica · 延迟 126 秒','紧急','2 分钟前','red'],['CPU 使用率持续偏高','pgsql-user-primary · 当前 82.4%','警告','18 分钟前','warning'],['磁盘空间不足','mysql-prod-order-01 · 剩余 12.8%','警告','36 分钟前','warning']];
const tasks=[['订单库慢查询分析','MySQL · 3 个实例 · 刘峰','已完成','success'],['生产库统计信息更新','PostgreSQL · 5 个实例 · 陈晨','执行中','running'],['Redis 过期键清理','Redis · 4 个实例 · 自动任务','待审批','pending']];
const instanceList=document.querySelector('#instanceList'),alertList=document.querySelector('#alertList'),taskList=document.querySelector('#taskList');
function renderInstances(filter='全部'){instanceList.innerHTML=instances.filter(x=>filter==='全部'||x[2]===filter).map(x=>`<div class="instance-row"><div class="db-name"><span class="db-icon ${x[2]==='PostgreSQL'?'pg':x[2]==='Redis'?'redis':''}">${x[2]==='MySQL'?'M':x[2]==='PostgreSQL'?'P':'R'}</span><span>${x[0]}<small>${x[1]}</small></span></div><span class="status ${x[3]!=='运行中'?'warn':''}">${x[3]}</span><span class="load">${x[4]}<span class="load-bar ${x[5]>70?'warn':''}"><i style="width:${x[5]}%"></i></span></span><button class="link">详情 →</button></div>`).join('')}
function renderAlerts(){alertList.innerHTML=alerts.map(a=>`<div class="alert-row"><span class="alert-sign ${a[4]}">${a[4]==='red'?'!':'!'}</span><div><b>${a[0]} <small class="tag ${a[4]==='red'?'pending':'pending'}">${a[2]}</small></b><p>${a[1]}</p></div><span class="time">${a[3]}</span></div>`).join('')}
function renderTasks(){taskList.innerHTML=tasks.map(t=>`<div class="task-row"><div><b>${t[0]}</b><p>${t[1]}</p></div><span class="tag ${t[3]}">${t[2]}</span></div>`).join('')}
renderInstances();renderAlerts();renderTasks();
document.querySelectorAll('.tabs button').forEach(btn=>btn.onclick=()=>{document.querySelector('.tabs .selected').classList.remove('selected');btn.classList.add('selected');renderInstances(btn.textContent.trim().replace(/\s+\d+/,''))});
const modal=document.querySelector('#modal'),toast=document.querySelector('#toast');document.querySelector('#newTask').onclick=()=>modal.classList.add('open');document.querySelector('#closeModal').onclick=document.querySelector('#closeModal2').onclick=()=>modal.classList.remove('open');
document.querySelector('#submitTask').onclick=()=>{modal.classList.remove('open');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)};
document.querySelector('#metricSelect').onchange=e=>document.querySelector('#currentMetric').textContent=e.target.selectedIndex===0?'62.4%':e.target.selectedIndex===1?'71.6%':'1,284';
document.querySelector('#viewHealth').onclick=()=>{toast.textContent='24 个实例中 23 个健康，1 个实例存在复制延迟';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)};

const groups={
 'SQL 质量与变更':[['sql-review','SQL 审核','开发、测试、生产全生命周期审核'],['sql-rewrite','SQL 智能改写','LLM 语义等价与性能验证'],['sql-window','SQL 窗口与执行','在线查询、计划查看与结果导出'],['tickets','工单管理','变更审批、执行和回滚'],['versions','版本列表','数据库 SQL 版本生命周期']],
 '运行保障':[['inspection','实例巡检','定时或立即巡检与性能洞察'],['performance','性能洞察','量化 SQL 资源消耗与优化建议'],['root-cause','根因诊断','异常 SQL 根因推导'],['locks','锁透视','锁等待、死锁及事务回放'],['slow-sql','慢 SQL 治理','慢 SQL 统计、样本和索引建议'],['sessions','会话与限流','实时会话分析和 SQL 限流'],['indexes','索引推荐','自动识别并生成优化 DDL'],['storage','存储分析','容量趋势预测与异常修复'],['parameters','参数调优与管理','AI 推荐与配置变更追溯'],['autonomy','自治管理','索引、限流和锁自治']],
 '数据安全':[['audit','审计日志','eBPF 采集、聚类与现场还原'],['schema-diff','结构对比','跨实例数据库对象对比'],['accounts','账号权限','数据库账号全生命周期管理']],
 '监控与报告':[['monitoring','基础监控','主机、进程和数据库自定义指标'],['alerts-config','告警管理','规则、模板、任务与多渠道通知'],['reports','报告中心','模板、下载、邮件和定时报告']],
 '智能服务':[['ai','AI 小助手','智能问答、智能体与功能引导']]
};
const nav=document.querySelector('#mainNav');
nav.innerHTML=`<p class="nav-title">运维中心</p><a class="nav-item active" data-feature="overview" href="#overview"><span>▦</span>Dashboard 大盘</a>${Object.entries(groups).map(([g,items])=>`<p class="nav-title space">${g}</p>${items.map((x,i)=>`<a class="nav-item" data-feature="${x[0]}" href="#${x[0]}"><span>${['◈','✦','▸','◇','◫'][i%5]}</span>${x[1]}${x[0]==='alerts-config'?'<em class="danger">3</em>':''}</a>`).join('')}`).join('')}`;
const featurePage=document.querySelector('#featurePage'),dashboard=document.querySelector('#dashboard');
let alertCenter,monitoringCenter;
document.addEventListener('DOMContentLoaded',()=>{const baseUrl=typeof window.DBPILOT_CONTROL_PLANE_URL==='string'?window.DBPILOT_CONTROL_PLANE_URL.trim():'';const alertContext=window.DBPilotAlertCenter.resolveAlertContext(baseUrl,window.DBPILOT_ALERT_CONTEXT);const showToast=(message)=>{toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)};alertCenter=window.DBPilotAlertCenter.create({root:featurePage,api:window.DBPilotAlertApi.create({baseUrl,available:alertContext.available}),scope:alertContext.scope,permissions:alertContext.permissions,onToast:showToast});monitoringCenter=window.DBPilotMonitoringCenter.create({root:featurePage,api:window.DBPilotMonitoringApi.create({baseUrl,available:alertContext.available}),scope:alertContext.scope,permissions:alertContext.permissions,onToast:showToast});const initialKey=window.location.hash.slice(1);const initialLink=nav.querySelector(`[data-feature="${CSS.escape(initialKey)}"]`);if(initialLink){nav.querySelector('.active')?.classList.remove('active');initialLink.classList.add('active');openFeature(initialKey)}});
const detail={'sql-review':['SQL 审核','从开发、测试到生产的 SQL 全生命周期质量管理','快速审核 · IDE 审核 · CI/CD 审核 · 代码仓审核','SQL 质量门禁','高风险 SQL 3 条','规则命中率 96.8%'],'inspection':['实例巡检','通过定时策略或立即巡检，统一发现实例风险并生成可追踪的巡检报告','立即巡检 · 定时巡检 · 自定义巡检项 · 性能异常现场还原','巡检策略','待处理问题 12 项','今日完成 8 次'],'reports':['报告中心','统一管理巡检与运维报告，按模板自动生成、下载和邮件分发','PDF / Word 导出 · 报告模板 · 邮件发送 · 定时生成','最近报告','本周生成 16 份','待发送 2 份'],'performance':['性能洞察','将单条 SQL 的资源消耗映射为可视化颜色面积，精准定位性能瓶颈','资源量化 · SQL 关联 · 优化建议 · 异常时刻还原','性能事件','高影响 SQL 7 条','资源节省 18.4%'],'locks':['锁透视','以环形图与泳道图回放锁等待、死锁、长事务和未提交事务','事务回放 · 加锁事件 · 等锁分析 · 根因定位','锁事件','当前等待 2 个','长事务 1 个'],'tickets':['工单管理','SQL 变更经过自动审核、人工审批、安全执行和回滚的完整闭环','DDL / DML 变更 · 审批流 · 执行历史 · 自动回滚 SQL','待审批工单','待处理 5 条','今日完成 12 条'],'ai':['AI 小助手','在聊天窗口中切换知识库问答与数据库运维智能体','实例问答 · 慢 SQL 查看 · 执行巡检 · 根因诊断','智能体任务','今日会话 28 次','已解决 22 个']};
function openFeature(key){if(key==='overview'){featurePage.classList.remove('open');dashboard.style.display='grid';document.querySelector('.health-banner').style.display='flex';document.querySelector('.stats-grid').style.display='grid';return}dashboard.style.display='none';document.querySelector('.health-banner').style.display='none';document.querySelector('.stats-grid').style.display='none';featurePage.classList.add('open');if(key==='alerts-config'){alertCenter?.open('overview');return}if(key==='monitoring'){monitoringCenter?.open('overview');return}const meta=detail[key]||[...Object.values(groups).flat()].find(x=>x[0]===key);const [title,desc,cap='规则配置 · 实时分析 · 历史记录 · 导出报告',list='待处理项目',v1='8 项',v2='运行正常']=meta;featurePage.innerHTML=`<div class="feature-hero"><span class="eyebrow">DBPILOT · ${title}</span><h2>${title}</h2><p>${desc}</p><div class="feature-actions"><button class="primary">＋ 创建任务</button><button class="secondary">查看使用指南</button></div></div><div class="feature-grid">${cap.split(' · ').map((x,i)=>`<article class="feature-card"><span class="feature-icon">${['◈','⌁','◇','✦'][i%4]}</span><h3>${x}</h3><p>面向生产环境提供可配置、可审计的统一运维能力，支持按项目与实例进行精细化管理。</p><footer><span>已启用</span><button>进入模块 →</button></footer></article>`).join('')}</div><article class="feature-table"><h3>${list}</h3><p>数据基于当前生产环境演示，接入真实服务后将实时更新。</p><div class="table-row"><span>对象 / 任务</span><span>所属实例</span><span>最近更新时间</span><span>状态</span></div><div class="table-row"><b>${title} · 风险分析任务</b><span>mysql-prod-order-01</span><span>2 分钟前</span><span class="tag pending">${v1}</span></div><div class="table-row"><b>${title} · 例行检查</b><span>pgsql-user-primary</span><span>18 分钟前</span><span class="tag success">${v2}</span></div></article>`}
nav.querySelectorAll('.nav-item').forEach(a=>a.onclick=()=>{nav.querySelector('.active').classList.remove('active');a.classList.add('active');openFeature(a.dataset.feature)});
document.body.insertAdjacentHTML('beforeend','<button class="ai-float" id="aiFloat">✦ AI 小助手</button>');document.querySelector('#aiFloat').onclick=()=>nav.querySelector('[data-feature="ai"]').click();
