[Unit]
Requires=dbpilot-agent-proc-helper.socket dbpilot-agent-proc-helper.service
After=dbpilot-agent-proc-helper.socket dbpilot-agent-proc-helper.service

[Service]
CapabilityBoundingSet=
AmbientCapabilities=
